remote: true

experienceLevel:
  internship: false
  entry: true
  associate: true
  mid-senior level: true
  director: false
  executive: false

jobTypes:
  full-time: true
  contract: true
  part-time: true
  temporary: true
  internship: false
  other: true
  volunteer: true

date:
  all time: false
  month: false
  week: false
  24 hours: true

positions:
  - Software engineer
  - Senior software engineer
  - Full Stack
  - Frontend
  - Backend

locations:
  - USA
  - United States of America
  - New York

apply_once_at_company: true

distance: 100

company_blacklist:

title_blacklist:

job_applicants_threshold:
  min_applicants: 0
  max_applicants:

llm_model_type: openai
llm_model: 'gpt-4o-mini'
# llm_api_url: https://api.pawan.krd/cosmosrp/v1'
